/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LiquorRouteImport } from './routes/liquor'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as OrdersConfirmationRouteImport } from './routes/orders.confirmation'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCodeRouteImport } from './routes/staff.$code'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersCodeRouteImport } from './routes/admin.orders.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquorRoute = LiquorRouteImport.update({
  id: '/liquor',
  path: '/liquor',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersConfirmationRoute = OrdersConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => OrdersRoute,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCodeRoute = StaffCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => StaffRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersCodeRoute = AdminOrdersCodeRouteImport.update({
  id: '/orders/$code',
  path: '/orders/$code',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/favourites': typeof FavouritesRoute
  '/help': typeof HelpRoute
  '/liquor': typeof LiquorRoute
  '/lists': typeof ListsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/problem': typeof ProblemRoute
  '/search': typeof SearchRoute
  '/shopping-list': typeof ShoppingListRoute
  '/staff': typeof StaffRouteWithChildren
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/confirmation': typeof OrdersConfirmationRoute
  '/payment/$id': typeof PaymentIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/staff/$code': typeof StaffCodeRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/orders/$code': typeof AdminOrdersCodeRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/favourites': typeof FavouritesRoute
  '/help': typeof HelpRoute
  '/liquor': typeof LiquorRoute
  '/lists': typeof ListsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/problem': typeof ProblemRoute
  '/search': typeof SearchRoute
  '/shopping-list': typeof ShoppingListRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/confirmation': typeof OrdersConfirmationRoute
  '/payment/$id': typeof PaymentIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/staff/$code': typeof StaffCodeRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/orders/$code': typeof AdminOrdersCodeRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/favourites': typeof FavouritesRoute
  '/help': typeof HelpRoute
  '/liquor': typeof LiquorRoute
  '/lists': typeof ListsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/problem': typeof ProblemRoute
  '/search': typeof SearchRoute
  '/shopping-list': typeof ShoppingListRoute
  '/staff': typeof StaffRouteWithChildren
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/category/$slug': typeof CategorySlugRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/confirmation': typeof OrdersConfirmationRoute
  '/payment/$id': typeof PaymentIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/staff/$code': typeof StaffCodeRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/orders/$code': typeof AdminOrdersCodeRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/addresses'
    | '/admin'
    | '/auth'
    | '/basket'
    | '/checkout'
    | '/disclaimer'
    | '/favourites'
    | '/help'
    | '/liquor'
    | '/lists'
    | '/orders'
    | '/privacy'
    | '/problem'
    | '/search'
    | '/shopping-list'
    | '/staff'
    | '/stores'
    | '/terms'
    | '/admin/requests'
    | '/admin/staff'
    | '/category/$slug'
    | '/order/$id'
    | '/orders/confirmation'
    | '/payment/$id'
    | '/product/$slug'
    | '/receipt/$id'
    | '/staff/$code'
    | '/store/$slug'
    | '/admin/'
    | '/staff/'
    | '/admin/orders/$code'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/addresses'
    | '/auth'
    | '/basket'
    | '/checkout'
    | '/disclaimer'
    | '/favourites'
    | '/help'
    | '/liquor'
    | '/lists'
    | '/orders'
    | '/privacy'
    | '/problem'
    | '/search'
    | '/shopping-list'
    | '/stores'
    | '/terms'
    | '/admin/requests'
    | '/admin/staff'
    | '/category/$slug'
    | '/order/$id'
    | '/orders/confirmation'
    | '/payment/$id'
    | '/product/$slug'
    | '/receipt/$id'
    | '/staff/$code'
    | '/store/$slug'
    | '/admin'
    | '/staff'
    | '/admin/orders/$code'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/addresses'
    | '/admin'
    | '/auth'
    | '/basket'
    | '/checkout'
    | '/disclaimer'
    | '/favourites'
    | '/help'
    | '/liquor'
    | '/lists'
    | '/orders'
    | '/privacy'
    | '/problem'
    | '/search'
    | '/shopping-list'
    | '/staff'
    | '/stores'
    | '/terms'
    | '/admin/requests'
    | '/admin/staff'
    | '/category/$slug'
    | '/order/$id'
    | '/orders/confirmation'
    | '/payment/$id'
    | '/product/$slug'
    | '/receipt/$id'
    | '/staff/$code'
    | '/store/$slug'
    | '/admin/'
    | '/staff/'
    | '/admin/orders/$code'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BasketRoute: typeof BasketRoute
  CheckoutRoute: typeof CheckoutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FavouritesRoute: typeof FavouritesRoute
  HelpRoute: typeof HelpRoute
  LiquorRoute: typeof LiquorRoute
  ListsRoute: typeof ListsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProblemRoute: typeof ProblemRoute
  SearchRoute: typeof SearchRoute
  ShoppingListRoute: typeof ShoppingListRoute
  StaffRoute: typeof StaffRouteWithChildren
  StoresRoute: typeof StoresRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrderIdRoute: typeof OrderIdRoute
  PaymentIdRoute: typeof PaymentIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquor': {
      id: '/liquor'
      path: '/liquor'
      fullPath: '/liquor'
      preLoaderRoute: typeof LiquorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/confirmation': {
      id: '/orders/confirmation'
      path: '/confirmation'
      fullPath: '/orders/confirmation'
      preLoaderRoute: typeof OrdersConfirmationRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$code': {
      id: '/staff/$code'
      path: '/$code'
      fullPath: '/staff/$code'
      preLoaderRoute: typeof StaffCodeRouteImport
      parentRoute: typeof StaffRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$code': {
      id: '/admin/orders/$code'
      path: '/orders/$code'
      fullPath: '/admin/orders/$code'
      preLoaderRoute: typeof AdminOrdersCodeRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersCodeRoute: typeof AdminOrdersCodeRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRequestsRoute: AdminRequestsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersCodeRoute: AdminOrdersCodeRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersConfirmationRoute: typeof OrdersConfirmationRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersConfirmationRoute: OrdersConfirmationRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface StaffRouteChildren {
  StaffCodeRoute: typeof StaffCodeRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCodeRoute: StaffCodeRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BasketRoute: BasketRoute,
  CheckoutRoute: CheckoutRoute,
  DisclaimerRoute: DisclaimerRoute,
  FavouritesRoute: FavouritesRoute,
  HelpRoute: HelpRoute,
  LiquorRoute: LiquorRoute,
  ListsRoute: ListsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProblemRoute: ProblemRoute,
  SearchRoute: SearchRoute,
  ShoppingListRoute: ShoppingListRoute,
  StaffRoute: StaffRouteWithChildren,
  StoresRoute: StoresRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrderIdRoute: OrderIdRoute,
  PaymentIdRoute: PaymentIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
